version: '3.9'

services:
  rest-api:
    container_name: rest-api-optilyz-challenge
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./
    ports:
      - 3000:3000
